## MISSING VALUES

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"C:\Users\Keara\Downloads\Intro_Data_Science_with_Python\automobile.csv")

In [4]:
df.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160,5500,16,22,?

In [5]:
print(df.isnull().sum().sum())

0

In [6]:
df_auto = df

In [7]:
#replace ? with nan
df = df.replace('?', np.nan) 
print(df.isnull().sum().sum())

59

In [8]:
#print column names with nan
print(df.isnull().sum())
print([col for col in df.columns if df[col].isnull().any()])

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64
['normalized-losses', 'num-of-doors', 'bore', 'stroke', 'horsepower', 'peak-rpm', 'price']

In [9]:
#REMOVING NAN
#normalized losses
print(df['normalized-losses'])

df_temp = df[df['normalized-losses'].notnull()]
print(df_temp)
print(df_temp.isnull().sum())

0      NaN
1      NaN
2      NaN
3      164
4      164
      ...
200     95
201     95
202     95
203     95
204     95
Name: normalized-losses, Length: 205, dtype: object
     symboling normalized-losses   make fuel-type aspiration num-of-doors  \
3            2               164   audi       gas        std         four
4            2               164   audi       gas        std         four
6            1               158   audi       gas        std         four
8            1               158   audi       gas      turbo         four
10           2               192    bmw       gas        std          two
..         ...               ...    ...       ...        ...          ...
200         -1                95  volvo       gas        std         four
201         -1                95  volvo       gas      turbo         four
202         -1                95  volvo       gas        std         four
203         -1                95  volvo    diesel      turbo         four
204         -1                95  volvo       gas      turbo         four

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
3        sedan          fwd           front        99.8  ...          109
4        sedan          4wd           front        99.4  ...          136
6        sedan          fwd           front       105.8  ...          136
8        sedan          fwd           front       105.8  ...          131
10       sedan          rwd           front       101.2  ...          108
..         ...          ...             ...         ...  ...          ...
200      sedan          rwd           front       109.1  ...          141
201      sedan          rwd           front       109.1  ...          141
202      sedan          rwd           front       109.1  ...          173
203      sedan          rwd           front       109.1  ...          145
204      sedan          rwd           front       109.1  ...          141

     fuel-system  bore  stroke compression-ratio horsepower  peak-rpm  \
3           mpfi  3.19     3.4              10.0        102      5500
4           mpfi  3.19     3.4               8.0        115      5500
6           mpfi  3.19     3.4               8.5        110      5500
8           mpfi  3.13     3.4               8.3        140      5500
10          mpfi   3.5     2.8               8.8        101      5800
..           ...   ...     ...               ...        ...       ...
200         mpfi  3.78    3.15               9.5        114      5400
201         mpfi  3.78    3.15               8.7        160      5300
202         mpfi  3.58    2.87               8.8        134      5500
203          idi  3.01     3.4              23.0        106      4800
204         mpfi  3.78    3.15               9.5        114      5400

    city-mpg highway-mpg  price
3         24          30  13950
4         18          22  17450
6         19          25  17710
8         17          20  23875
10        23          29  16430
..       ...         ...    ...
200       23          28  16845
201       19          25  19045
202       18          23  21485
203       26          27  22470
204       19          25  22625

[164 rows x 26 columns]
symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         1
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 4
stroke               4
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [10]:
#IMPUTATION WITH MEAN
#print column types
print(df.dtypes)

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [11]:
#mean of normalized losses
print(df_temp['normalized-losses'].astype(int).mean())

col_mean = df_temp['normalized-losses'].astype(int).mean()

122.0

In [12]:
#impute mean
df['normalized-losses'] = df['normalized-losses'].replace(np.nan, col_mean).astype(int)

In [13]:
#IMPUTATION WITH MEDIAN
#peak rpm
print(df['peak-rpm'])

df_temp = df[df['peak-rpm'].notnull()]
print(df_temp)
print(df_temp.isnull().sum())

0      5000
1      5000
2      5000
3      5500
4      5500
       ...
200    5400
201    5300
202    5500
203    4800
204    5400
Name: peak-rpm, Length: 205, dtype: object
     symboling  normalized-losses         make fuel-type aspiration  \
0            3                122  alfa-romero       gas        std
1            3                122  alfa-romero       gas        std
2            1                122  alfa-romero       gas        std
3            2                164         audi       gas        std
4            2                164         audi       gas        std
..         ...                ...          ...       ...        ...
200         -1                 95        volvo       gas        std
201         -1                 95        volvo       gas      turbo
202         -1                 95        volvo       gas        std
203         -1                 95        volvo    diesel      turbo
204         -1                 95        volvo       gas      turbo

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
4           four        sedan          4wd           front        99.4  ...
..           ...          ...          ...             ...         ...  ...
200         four        sedan          rwd           front       109.1  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
203         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111
1            130         mpfi  3.47    2.68               9.0        111
2            152         mpfi  2.68    3.47               9.0        154
3            109         mpfi  3.19     3.4              10.0        102
4            136         mpfi  3.19     3.4               8.0        115
..           ...          ...   ...     ...               ...        ...
200          141         mpfi  3.78    3.15               9.5        114
201          141         mpfi  3.78    3.15               8.7        160
202          173         mpfi  3.58    2.87               8.8        134
203          145          idi  3.01     3.4              23.0        106
204          141         mpfi  3.78    3.15               9.5        114

     peak-rpm city-mpg highway-mpg  price
0        5000       21          27  13495
1        5000       21          27  16500
2        5000       19          26  16500
3        5500       24          30  13950
4        5500       18          22  17450
..        ...      ...         ...    ...
200      5400       23          28  16845
201      5300       19          25  19045
202      5500       18          23  21485
203      4800       26          27  22470
204      5400       19          25  22625

[203 rows x 26 columns]
symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         2
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 4
stroke               4
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                4
dtype: int64

In [15]:
#print column types
df.dtypes

symboling              int64
normalized-losses      int32
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [17]:
#median of peak-rpm
print(df_temp['peak-rpm'].astype(int).median())

col_med = df_temp['peak-rpm'].astype(int).median()

#impute median
df['peak-rpms'] = df['peak-rpm'].replace(np.nan, col_med).astype(int)

5200.0

In [18]:
#bore
print(df['bore'])

df_temp = df[df['bore'].notnull()]
print(df_temp)
print(df_temp.isnull().sum())

0      3.47
1      3.47
2      2.68
3      3.19
4      3.19
       ...
200    3.78
201    3.78
202    3.58
203    3.01
204    3.78
Name: bore, Length: 205, dtype: object
     symboling  normalized-losses         make fuel-type aspiration  \
0            3                122  alfa-romero       gas        std
1            3                122  alfa-romero       gas        std
2            1                122  alfa-romero       gas        std
3            2                164         audi       gas        std
4            2                164         audi       gas        std
..         ...                ...          ...       ...        ...
200         -1                 95        volvo       gas        std
201         -1                 95        volvo       gas      turbo
202         -1                 95        volvo       gas        std
203         -1                 95        volvo    diesel      turbo
204         -1                 95        volvo       gas      turbo

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
4           four        sedan          4wd           front        99.4  ...
..           ...          ...          ...             ...         ...  ...
200         four        sedan          rwd           front       109.1  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
203         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     fuel-system  bore  stroke  compression-ratio horsepower peak-rpm  \
0           mpfi  3.47    2.68                9.0        111     5000
1           mpfi  3.47    2.68                9.0        111     5000
2           mpfi  2.68    3.47                9.0        154     5000
3           mpfi  3.19     3.4               10.0        102     5500
4           mpfi  3.19     3.4                8.0        115     5500
..           ...   ...     ...                ...        ...      ...
200         mpfi  3.78    3.15                9.5        114     5400
201         mpfi  3.78    3.15                8.7        160     5300
202         mpfi  3.58    2.87                8.8        134     5500
203          idi  3.01     3.4               23.0        106     4800
204         mpfi  3.78    3.15                9.5        114     5400

     city-mpg highway-mpg  price peak-rpms
0          21          27  13495      5000
1          21          27  16500      5000
2          19          26  16500      5000
3          24          30  13950      5500
4          18          22  17450      5500
..        ...         ...    ...       ...
200        23          28  16845      5400
201        19          25  19045      5300
202        18          23  21485      5500
203        26          27  22470      4800
204        19          25  22625      5400

[201 rows x 27 columns]
symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         2
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                4
peak-rpms            0
dtype: int64

In [19]:
#print column types
print(df.dtypes)

#mean of bore
print(df_temp['bore'].astype(float).mean())

col_mean = df_temp['bore'].astype(float).mean()

#impute mean
df['bore'] = df['bore'].replace(np.nan, col_mean).astype(float)

symboling              int64
normalized-losses      int32
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
peak-rpms              int32
dtype: object
3.3297512437810957

In [21]:
#IMPUTATION WITH MOST FREQUENT
#stroke
print(df['stroke'])

0      2.68
1      2.68
2      3.47
3       3.4
4       3.4
       ...
200    3.15
201    3.15
202    2.87
203     3.4
204    3.15
Name: stroke, Length: 205, dtype: object

In [22]:
df_temp = df[df['stroke'].notnull()]
print(df_temp)
print(df_temp.isnull().sum())

     symboling  normalized-losses         make fuel-type aspiration  \
0            3                122  alfa-romero       gas        std
1            3                122  alfa-romero       gas        std
2            1                122  alfa-romero       gas        std
3            2                164         audi       gas        std
4            2                164         audi       gas        std
..         ...                ...          ...       ...        ...
200         -1                 95        volvo       gas        std
201         -1                 95        volvo       gas      turbo
202         -1                 95        volvo       gas        std
203         -1                 95        volvo    diesel      turbo
204         -1                 95        volvo       gas      turbo

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
4           four        sedan          4wd           front        99.4  ...
..           ...          ...          ...             ...         ...  ...
200         four        sedan          rwd           front       109.1  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
203         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     fuel-system  bore  stroke  compression-ratio horsepower peak-rpm  \
0           mpfi  3.47    2.68                9.0        111     5000
1           mpfi  3.47    2.68                9.0        111     5000
2           mpfi  2.68    3.47                9.0        154     5000
3           mpfi  3.19     3.4               10.0        102     5500
4           mpfi  3.19     3.4                8.0        115     5500
..           ...   ...     ...                ...        ...      ...
200         mpfi  3.78    3.15                9.5        114     5400
201         mpfi  3.78    3.15                8.7        160     5300
202         mpfi  3.58    2.87                8.8        134     5500
203          idi  3.01     3.4               23.0        106     4800
204         mpfi  3.78    3.15                9.5        114     5400

     city-mpg highway-mpg  price peak-rpms
0          21          27  13495      5000
1          21          27  16500      5000
2          19          26  16500      5000
3          24          30  13950      5500
4          18          22  17450      5500
..        ...         ...    ...       ...
200        23          28  16845      5400
201        19          25  19045      5300
202        18          23  21485      5500
203        26          27  22470      4800
204        19          25  22625      5400

[201 rows x 27 columns]
symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         2
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                4
peak-rpms            0
dtype: int64

In [23]:
#print column types
print(df.dtypes)

symboling              int64
normalized-losses      int32
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                 float64
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
peak-rpms              int32
dtype: object

In [24]:
#most frequent of stroke
print(df_temp['stroke'].value_counts())
print(df_temp['stroke'].value_counts().index[0])

most_frequent = df_temp['stroke'].value_counts().index[0]

3.4     20
3.23    14
3.03    14
3.15    14
3.39    13
2.64    11
3.35     9
3.29     9
3.46     8
3.27     6
3.5      6
3.07     6
3.11     6
3.41     6
3.19     6
3.58     6
3.64     5
3.52     5
3.54     4
3.86     4
3.47     4
3.9      3
2.9      3
4.17     2
3.08     2
2.68     2
2.8      2
3.1      2
2.19     2
3.16     1
2.07     1
3.21     1
2.36     1
2.76     1
3.12     1
2.87     1
Name: stroke, dtype: int64
3.4

In [25]:
#impute most frequent
df['stroke'] = df['stroke'].replace(np.nan, most_frequent).astype(float)

In [26]:
#num-of-doors
print(df['num-of-doors'])

0       two
1       two
2       two
3      four
4      four
       ...
200    four
201    four
202    four
203    four
204    four
Name: num-of-doors, Length: 205, dtype: object

In [28]:
df_temp = df[df['num-of-doors'].notnull()]
print(df_temp['num-of-doors'].value_counts())

four    114
two      89
Name: num-of-doors, dtype: int64

In [29]:
#impute most frequent
df['num-of-doors'] = df['num-of-doors'].fillna(df_temp['num-of-doors'].value_counts().index[0])

print(df.describe())

        symboling  normalized-losses  wheel-base      length       width  \
count  205.000000         205.000000  205.000000  205.000000  205.000000
mean     0.834146         122.000000   98.756585  174.049268   65.907805
std      1.245307          31.681008    6.021776   12.337289    2.145204
min     -2.000000          65.000000   86.600000  141.100000   60.300000
25%      0.000000         101.000000   94.500000  166.300000   64.100000
50%      1.000000         122.000000   97.000000  173.200000   65.500000
75%      2.000000         137.000000  102.400000  183.100000   66.900000
max      3.000000         256.000000  120.900000  208.100000   72.300000

           height  curb-weight  engine-size        bore      stroke  \
count  205.000000   205.000000   205.000000  205.000000  205.000000
mean    53.724878  2555.565854   126.907317    3.329751    3.258244
std      2.443522   520.680204    41.642693    0.270844    0.314237
min     47.800000  1488.000000    61.000000    2.540000    2.070000
25%     52.000000  2145.000000    97.000000    3.150000    3.110000
50%     54.100000  2414.000000   120.000000    3.310000    3.290000
75%     55.500000  2935.000000   141.000000    3.580000    3.410000
max     59.800000  4066.000000   326.000000    3.940000    4.170000

       compression-ratio    city-mpg  highway-mpg    peak-rpms
count         205.000000  205.000000   205.000000   205.000000
mean           10.142537   25.219512    30.751220  5126.097561
std             3.972040    6.542142     6.886443   477.035772
min             7.000000   13.000000    16.000000  4150.000000
25%             8.600000   19.000000    25.000000  4800.000000
50%             9.000000   24.000000    30.000000  5200.000000
75%             9.400000   30.000000    34.000000  5500.000000
max            23.000000   49.000000    54.000000  6600.000000